/*
 * step_4_3
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateUser {
    #[serde(rename = "email", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub email: Option<Option<String>>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "roleSlug")]
    pub role_slug: String,
}

impl CreateUser {
    pub fn new(name: String, role_slug: String) -> CreateUser {
        CreateUser {
            email: None,
            name,
            role_slug,
        }
    }
}


