/*
 * step_4_3
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Permissions {
    #[serde(rename = "reader")]
    Reader,
    #[serde(rename = "editor")]
    Editor,
    #[serde(rename = "admin")]
    Admin,

}

impl ToString for Permissions {
    fn to_string(&self) -> String {
        match self {
            Self::Reader => String::from("reader"),
            Self::Editor => String::from("editor"),
            Self::Admin => String::from("admin"),
        }
    }
}

impl Default for Permissions {
    fn default() -> Permissions {
        Self::Reader
    }
}




