/*
 * step_4_3
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateUser {
    #[serde(rename = "add_roles", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub add_roles: Option<Option<Vec<String>>>,
    #[serde(rename = "email", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub email: Option<Option<String>>,
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    #[serde(rename = "remove_roles", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub remove_roles: Option<Option<Vec<String>>>,
}

impl UpdateUser {
    pub fn new() -> UpdateUser {
        UpdateUser {
            add_roles: None,
            email: None,
            name: None,
            remove_roles: None,
        }
    }
}


