/*
 * step_4_3
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UserWithRoles {
    #[serde(rename = "email", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub email: Option<Option<String>>,
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "roles")]
    pub roles: Vec<crate::models::RolesPeriodModel>,
}

impl UserWithRoles {
    pub fn new(id: i32, name: String, roles: Vec<crate::models::RolesPeriodModel>) -> UserWithRoles {
        UserWithRoles {
            email: None,
            id,
            name,
            roles,
        }
    }
}


