/*
 * step_4_3
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UserWithRolesAllOf {
    #[serde(rename = "roles")]
    pub roles: Vec<crate::models::RolesPeriodModel>,
}

impl UserWithRolesAllOf {
    pub fn new(roles: Vec<crate::models::RolesPeriodModel>) -> UserWithRolesAllOf {
        UserWithRolesAllOf {
            roles,
        }
    }
}


