//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.1

use clap::ValueEnum;
use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, ValueEnum)]
#[value(rename_all = "snake_case")]
#[sea_orm(rs_type = "String", db_type = "String(Some(256))")]
pub enum Permissions {
    #[sea_orm(string_value = "reader")]
    Reader,
    #[sea_orm(string_value = "editor")]
    Editor,
    #[sea_orm(string_value = "admin")]
    Admin,
}

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "roles")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub slug: String,
    pub name: String,
    pub permissions: Permissions,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
