[package]
name = "step_4"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
async-trait = "0.1.72"
axum = "0.6.19"
juniper = "0.15.11"
serde_json = "1.0.104"
thiserror = "1.0.44"
tokio = { version = "1.29.1", features = ["full"] }
