[package]
name = "step_3_10"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
crossbeam = "0.8.2"
ndarray = { version = "0.15.6", features = ["rayon"] }
ndarray-rand = "0.14.0"
rand = "0.8.5"
rayon = "1.7.0"
