[package]
name = "step_4_2_client"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.72"
reqwest = { version = "0.11.18", default-features = false, features = ["blocking", "json"] }
