[package]
name = "step_3_8"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
dairy = "0.2.2"
serde = "1.0.175"
serde_json = "1.0.103"
time = { version = "0.3.23", features = ["formatting"] }
tracing = "0.1.37"
tracing-serde = "0.1.3"
tracing-subscriber = "0.3.17"
